# Generated by Django 3.2 on 2022-10-20 16:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_guid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('account_owner', models.CharField(max_length=255)),
                ('department_name', models.CharField(max_length=255)),
                ('account_name', models.CharField(max_length=255)),
                ('account_type', models.CharField(max_length=255)),
                ('supplier_tier', models.CharField(max_length=255)),
                ('customer_agent', models.CharField(max_length=255)),
                ('sales_3y', models.DecimalField(decimal_places=2, max_digits=15)),
                ('sales_cy', models.DecimalField(decimal_places=2, max_digits=15)),
                ('margin_3y', models.DecimalField(decimal_places=2, max_digits=15)),
                ('margin_cy', models.DecimalField(decimal_places=2, max_digits=15)),
                ('open_quotes', models.DecimalField(decimal_places=2, max_digits=15)),
                ('last_activity', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=4000)),
                ('as_of_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
