# Generated by Django 3.2 on 2022-11-25 13:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripvisit',
            name='ads_participants',
            field=models.ManyToManyField(blank=True, related_name='ads_visits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tripvisit',
            name='external_participants',
            field=models.ManyToManyField(blank=True, related_name='external_visits', to=settings.AUTH_USER_MODEL),
        ),
    ]
